Break image build if the l-m-x image file is missing

diff --git a/finnix-live-build b/finnix-live-build
--- a/finnix-live-build
+++ b/finnix-live-build
@@ -410,11 +410,13 @@ mkdir -p "${LB_DIR}/config/package-lists"
 cp -a "${RENDER_DIR}/package-lists/." "${LB_DIR}/config/package-lists/"
 
 # Include l-m-x image and scripts
-if [ -d "${LAMASSU_EXTRAS}" ]; then
-    mkdir -p "${LB_DIR}/config/includes.chroot_after_packages/opt/lamassu/"
-    echo >&2 "Copying ${LAMASSU_EXTRAS} to chroot..."
-    cp -a "${LAMASSU_EXTRAS}"/* -t "${LB_DIR}/config/includes.chroot_after_packages/opt/lamassu/"
+if [ ! -f "${LAMASSU_IMAGE_DIR}/image.img.gz" ]; then # Path to *.img.gz etc
+    echo >&2 "Image file '${LAMASSU_IMAGE_DIR}/image.img.gz' does not exist; cannot proceed."
+    exit 1
 fi
+mkdir -p "${LB_DIR}/config/includes.chroot_after_packages/opt/lamassu/"
+cp -a lamassu-extras/* -t "${LB_DIR}/config/includes.chroot_after_packages/opt/lamassu/"
+cp -a "${LAMASSU_IMAGE_DIR}"/image.img.* -t "${LB_DIR}/config/includes.chroot_after_packages/opt/lamassu/"
 
 if [ "${is_dirty}" = "true" ]; then
     mkdir -p "${LB_DIR}/config/includes.binary/.disk"
